#include "stdafx.h"
#include "Problem0002.h"

using namespace ProjectEuler;

Problem0002::Problem0002()
	: ProblemBase()
{
	_initializeProblemStatement();
}

Problem0002::~Problem0002()
{
}

void Problem0002::_initializeProblemStatement()
{
	_problemStatement = "Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be : 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.";
}

void Problem0002::solve()
{
	long limit = 4000000;
	vector<long> f = _math->FibonacciSeriesLimit(limit);

	int nTerms = f.size();

	_answer = 0.0;

	for (int i = 0; i < nTerms; ++i)
	{
		if (_math->IsEven(f[i]))
		{
			_answer += f[i];
		}
	}
}
